### ISSUE TITLE
DB Kurulum Hatası

### ISSUE THREAD

**Issue by MuhammetDilmac** [rubytr/ruby-tr#82]
Selamlar,
Active Admin'de admin_collection metodunun proc içinde çalıştırılmaması sebebi ile db kurulurken active_admin hata fırlatıyor.

```
 ✘ muhammet@adeo  ~/Projects/ruby/ruby-tr   67-sosyal-medya-hesaplari  bin/setup           
== Installing dependencies ==
Warning: the running version of Bundler (1.15.4) is older than the version that created the lockfile (1.16.0.pre.2). We suggest you upgrade to the latest version of Bundler by running `gem install bundler --pre`.
The Gemfile's dependencies are satisfied

== Preparing database ==
Database 'db/development.sqlite3' already exists
Database 'db/test.sqlite3' already exists
rails aborted!
ActiveAdmin::DatabaseHitDuringLoad: Your file, app/admin/announcement.rb (line 2), caused a database error while Active Admin was loading. This is most common when your database is missing or doesn't have the latest migrations applied. To prevent this error, move the code to a place where it will only be run when a page is rendered. One solution can be, to wrap the query in a Proc. Original error message: SQLite3::SQLException: no such table: admin_users: SELECT "admin_users".* FROM "admin_users"
/home/muhammet/Projects/ruby/ruby-tr/config/routes.rb:3:in `block in <top (required)>'
/home/muhammet/Projects/ruby/ruby-tr/config/routes.rb:1:in `<top (required)>'
/home/muhammet/Projects/ruby/ruby-tr/config/environment.rb:5:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
ActiveRecord::StatementInvalid: SQLite3::SQLException: no such table: admin_users: SELECT "admin_users".* FROM "admin_users"
/home/muhammet/Projects/ruby/ruby-tr/app/admin/announcement.rb:2:in `map'
/home/muhammet/Projects/ruby/ruby-tr/app/admin/announcement.rb:2:in `admin_collection'
/home/muhammet/Projects/ruby/ruby-tr/app/admin/announcement.rb:17:in `block in <top (required)>'
/home/muhammet/Projects/ruby/ruby-tr/app/admin/announcement.rb:5:in `<top (required)>'
/home/muhammet/Projects/ruby/ruby-tr/config/routes.rb:3:in `block in <top (required)>'
/home/muhammet/Projects/ruby/ruby-tr/config/routes.rb:1:in `<top (required)>'
/home/muhammet/Projects/ruby/ruby-tr/config/environment.rb:5:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
SQLite3::SQLException: no such table: admin_users
/home/muhammet/Projects/ruby/ruby-tr/app/admin/announcement.rb:2:in `map'
/home/muhammet/Projects/ruby/ruby-tr/app/admin/announcement.rb:2:in `admin_collection'
/home/muhammet/Projects/ruby/ruby-tr/app/admin/announcement.rb:17:in `block in <top (required)>'
/home/muhammet/Projects/ruby/ruby-tr/app/admin/announcement.rb:5:in `<top (required)>'
/home/muhammet/Projects/ruby/ruby-tr/config/routes.rb:3:in `block in <top (required)>'
/home/muhammet/Projects/ruby/ruby-tr/config/routes.rb:1:in `<top (required)>'
/home/muhammet/Projects/ruby/ruby-tr/config/environment.rb:5:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:setup => db:schema:load_if_ruby => environment
(See full trace by running task with --trace)

== Command ["bin/rails db:setup"] failed ==
```

**Comment by enderahmetyurt** [comment]
Evet @MuhammetDilmac e katılıyorum. @muratbsts bu konuya bakar mısın?

**Comment by muratbsts** [comment]
Bakarım @enderahmetyurt 👍

**Comment by enderahmetyurt** [comment]
@muratbsts yok abi @MuhammetDilmac yapmış bile. ben fark etmemişim.
